{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "7e55c1ba-392c-4c85-8693-e36324ba761c",
   "metadata": {},
   "outputs": [],
   "source": [
    "def shift_letter(letter, shift):\n",
    "    '''Shift Letter. \n",
    "    5 points.\n",
    "    \n",
    "    Shift a letter right by the given number.\n",
    "    Wrap the letter around if it reaches the end of the alphabet.\n",
    "    Examples:\n",
    "    shift_letter(\"A\", 0) -> \"A\"\n",
    "    shift_letter(\"A\", 2) -> \"C\"\n",
    "    shift_letter(\"Z\", 1) -> \"A\"\n",
    "    shift_letter(\"X\", 5) -> \"C\"\n",
    "    shift_letter(\" \", _) -> \" \"\n",
    "    *Note: the single underscore `_` is used to acknowledge the presence\n",
    "        of a value without caring about its contents.\n",
    "    Parameters\n",
    "    ----------\n",
    "    letter: str\n",
    "        a single uppercase English letter, or a space.\n",
    "    shift: int\n",
    "        the number by which to shift the letter. \n",
    "    Returns\n",
    "    -------\n",
    "    str\n",
    "        the letter, shifted appropriately, if a letter.\n",
    "        a single space if the original letter was a space.\n",
    "    '''\n",
    "    # Replace `pass` with your code. \n",
    "    # Stay within the function. Only use the parameters as input. The function should return your answer.\n",
    "    \n",
    "    def shift_letter(letter, shift):\n",
    "        is_upper = letter.isupper()\n",
    "        num_letter = ord(letter)\n",
    "        total = shift + num_letter\n",
    "        if letter == \" \":\n",
    "            return \" \"\n",
    "        elif letter == \"_\":\n",
    "            return \" \"\n",
    "        elif is_upper:\n",
    "            max = 90\n",
    "            if total > max:\n",
    "                remainder = int(total - 90 + 65)\n",
    "                new_letter = (chr(remainder-1))\n",
    "                return(new_letter)\n",
    "            else: \n",
    "                new_letter = chr(num_letter+shift)\n",
    "                return (new_letter)\n",
    "        else:\n",
    "            max = 122\n",
    "            if total > max:\n",
    "                remainder = int(total - 122 + 97)\n",
    "                new_letter = (chr(remainder-1))\n",
    "                return(new_letter)\n",
    "            else: \n",
    "                new_letter = chr(num_letter+shift)\n",
    "                return (new_letter)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "797b0a23-4f29-4f48-bc5b-f8fe31abf2c4",
   "metadata": {},
   "outputs": [],
   "source": [
    "def caesar_cipher(message, shift):\n",
    "    '''Caesar Cipher. \n",
    "    10 points.\n",
    "    \n",
    "    Apply a shift number to a string of uppercase English letters and spaces.\n",
    "    Parameters\n",
    "    ----------\n",
    "    message: str\n",
    "        a string of uppercase English letters and spaces.\n",
    "    shift: int\n",
    "        the number by which to shift the letters. \n",
    "    Returns\n",
    "    -------\n",
    "    str\n",
    "        the message, shifted appropriately.\n",
    "    '''\n",
    "    # Replace `pass` with your code. \n",
    "    # Stay within the function. Only use the parameters as input. The function should return your answer.\n",
    "    \n",
    "    def caesar_cipher(message, shift):\n",
    "        list=[]\n",
    "        for i in message: \n",
    "            list.append(i)\n",
    "        new=[]\n",
    "  \n",
    "        for i in list:\n",
    "            letter = i\n",
    "            is_upper = letter.isupper()\n",
    "            if is_upper:\n",
    "                num_letter = ord(i)\n",
    "                total = shift + num_letter\n",
    "                max = 90\n",
    "                if i == \" \":\n",
    "                    new.append(\" \")\n",
    "                elif i == \"_\":\n",
    "                    new.append(\"_\")\n",
    "                else:\n",
    "                    if total > max:\n",
    "                        remainder = int(total - 90 + 65)\n",
    "                        new_letter = (chr(remainder-1))\n",
    "                        new.append(new_letter)\n",
    "                    else: \n",
    "                        new_letter = chr(num_letter+shift)\n",
    "                        new.append(new_letter)\n",
    "                    c_cipher =\"\"\n",
    "                    c_cipher =c_cipher.join(new)\n",
    "            else:\n",
    "                num_letter = ord(i)\n",
    "                total = shift + num_letter\n",
    "                max = 122\n",
    "                if i == \" \":\n",
    "                    new.append(\" \")\n",
    "                elif i == \"_\":\n",
    "                    new.append(\"_\")\n",
    "                else:\n",
    "                    if total > max:\n",
    "                        remainder = int(total - 122 + 97)\n",
    "                        new_letter = (chr(remainder-1))\n",
    "                        new.append(new_letter)\n",
    "                    else: \n",
    "                        new_letter = chr(num_letter+shift)\n",
    "                        new.append(new_letter)\n",
    "                    c_cipher =\"\"\n",
    "                    c_cipher =c_cipher.join(new)\n",
    "        return c_cipher"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "1a5671a5-8792-4ef3-ba10-2ad772ee6d0a",
   "metadata": {},
   "outputs": [],
   "source": [
    "def shift_by_letter(letter, letter_shift):\n",
    "    '''Shift By Letter. \n",
    "    10 points.\n",
    "    \n",
    "    Shift a letter to the right using the number equivalent of another letter.\n",
    "    The shift letter is any letter from A to Z, where A represents 0, B represents 1, \n",
    "        ..., Z represents 25.\n",
    "    Examples:\n",
    "    shift_by_letter(\"A\", \"A\") -> \"A\"\n",
    "    shift_by_letter(\"A\", \"C\") -> \"C\"\n",
    "    shift_by_letter(\"B\", \"K\") -> \"L\"\n",
    "    shift_by_letter(\" \", _) -> \" \"\n",
    "    Parameters\n",
    "    ----------\n",
    "    letter: str\n",
    "        a single uppercase English letter, or a space.\n",
    "    letter_shift: str\n",
    "        a single uppercase English letter.\n",
    "    Returns\n",
    "    -------\n",
    "    str\n",
    "        the letter, shifted appropriately.\n",
    "    '''\n",
    "    # Replace `pass` with your code. \n",
    "    # Stay within the function. Only use the parameters as input. The function should return your answer.\n",
    "    \n",
    "    def shift_by_letter(letter, letter_shift):\n",
    "      Alphabet = [\"A\",\"B\",\"C\",\"D\",\"E\",\"F\",\"G\",\"H\",\"I\",\"J\",'K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z']\n",
    "      output =\"\"\n",
    "      if letter == \" \":\n",
    "        output = \" \" \n",
    "      elif letter == \"_\":\n",
    "        output=\"_\"\n",
    "      else:\n",
    "        letter_val= Alphabet.index(letter)\n",
    "        shift_val= int(Alphabet.index(letter_shift)+Alphabet.index(letter))\n",
    "        if shift_val+letter_val > 25:\n",
    "          shift_val= int(Alphabet.index(letter_shift)+Alphabet.index(letter)) - 26\n",
    "          shifted_let = Alphabet[shift_val]\n",
    "          output = shifted_let\n",
    "        else:\n",
    "          shift_val= int(Alphabet.index(letter_shift)+Alphabet.index(letter))\n",
    "          shifted_let = Alphabet[shift_val]\n",
    "          output = shifted_let\n",
    "        return (output)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "9008d0a4-aba3-474f-b4c2-851fdbe643e6",
   "metadata": {},
   "outputs": [],
   "source": [
    "def shift_by_letter(letter, letter_shift):\n",
    "    '''Shift By Letter. \n",
    "    10 points.\n",
    "    \n",
    "    Shift a letter to the right using the number equivalent of another letter.\n",
    "    The shift letter is any letter from A to Z, where A represents 0, B represents 1, \n",
    "        ..., Z represents 25.\n",
    "    Examples:\n",
    "    shift_by_letter(\"A\", \"A\") -> \"A\"\n",
    "    shift_by_letter(\"A\", \"C\") -> \"C\"\n",
    "    shift_by_letter(\"B\", \"K\") -> \"L\"\n",
    "    shift_by_letter(\" \", _) -> \" \"\n",
    "    Parameters\n",
    "    ----------\n",
    "    letter: str\n",
    "        a single uppercase English letter, or a space.\n",
    "    letter_shift: str\n",
    "        a single uppercase English letter.\n",
    "    Returns\n",
    "    -------\n",
    "    str\n",
    "        the letter, shifted appropriately.\n",
    "    '''\n",
    "    # Replace `pass` with your code. \n",
    "    # Stay within the function. Only use the parameters as input. The function should return your answer.\n",
    "    \n",
    "    def shift_by_letter(letter, letter_shift):\n",
    "      Alphabet = [\"A\",\"B\",\"C\",\"D\",\"E\",\"F\",\"G\",\"H\",\"I\",\"J\",'K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z']\n",
    "      output =\"\"\n",
    "      if letter == \" \":\n",
    "        output = \" \" \n",
    "      elif letter == \"_\":\n",
    "        output=\"_\"\n",
    "      else:\n",
    "        letter_val= Alphabet.index(letter)\n",
    "        shift_val= int(Alphabet.index(letter_shift)+Alphabet.index(letter))\n",
    "        if shift_val+letter_val > 25:\n",
    "          shift_val= int(Alphabet.index(letter_shift)+Alphabet.index(letter)) - 26\n",
    "          shifted_let = Alphabet[shift_val]\n",
    "          output = shifted_let\n",
    "        else:\n",
    "          shift_val= int(Alphabet.index(letter_shift)+Alphabet.index(letter))\n",
    "          shifted_let = Alphabet[shift_val]\n",
    "          output = shifted_let\n",
    "        return (output)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "8521d819-26a5-4cd6-b831-bd5e23306129",
   "metadata": {},
   "outputs": [],
   "source": [
    "def vigenere_cipher(message, key):\n",
    "    '''Vigenere Cipher. \n",
    "    15 points.\n",
    "    \n",
    "    Encrypts a message using a keyphrase instead of a static number.\n",
    "    Every letter in the message is shifted by the number represented by the \n",
    "        respective letter in the key.\n",
    "    Spaces should be ignored.\n",
    "    Example:\n",
    "    vigenere_cipher(\"A C\", \"KEY\") -> \"K A\"\n",
    "    If needed, the keyphrase is extended to match the length of the key.\n",
    "        If the key is \"KEY\" and the message is \"LONGTEXT\",\n",
    "        the key will be extended to be \"KEYKEYKE\".\n",
    "    Parameters\n",
    "    ----------\n",
    "    message: str\n",
    "        a string of uppercase English letters and spaces.\n",
    "    key: str\n",
    "        a string of uppercase English letters. Will never be longer than the message.\n",
    "        Will never contain spaces.\n",
    "    Returns\n",
    "    -------\n",
    "    str\n",
    "        the message, shifted appropriately.\n",
    "    '''\n",
    "    # Replace `pass` with your code. \n",
    "    # Stay within the function. Only use the parameters as input. The function should return your answer.\n",
    "    \n",
    "    def vigenere_cipher(message, key):\n",
    "        Alphabet = [\"A\",\"B\",\"C\",\"D\",\"E\",\"F\",\"G\",\"H\",\"I\",\"J\",'K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z']\n",
    "        orig=[]\n",
    "        shift=[]\n",
    "        shifted=[]\n",
    "        output=\"\"\n",
    "  \n",
    "        for i in message: \n",
    "          orig.append(i)\n",
    "        for i in key:\n",
    "          shift.append(i)\n",
    "  \n",
    "        for i in range(len(message)):\n",
    "          if orig[i] == \" \": \n",
    "            shifted.append(\" \")\n",
    "          elif orig[i] == \"_\": \n",
    "            shifted.append(\"_\")\n",
    "          else: \n",
    "            val = int(Alphabet.index(orig[i]) + Alphabet.index(shift[i]))\n",
    "            if val > 25:\n",
    "              val = (val-25)\n",
    "              shifted.append(Alphabet[val-1])\n",
    "            else:\n",
    "              shifted.append(Alphabet[val])\n",
    "        output= output.join(shifted)\n",
    "        return (output)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "88d77c96-b16c-49ce-ac03-a4b11774562d",
   "metadata": {},
   "outputs": [],
   "source": [
    "def scytale_cipher(message, shift):\n",
    "    '''Scytale Cipher.\n",
    "    15 points.\n",
    "    \n",
    "    Encrypts a message by simulating a scytale cipher.\n",
    "    A scytale is a cylinder around which you can wrap a long strip of \n",
    "        parchment that contained a string of apparent gibberish. The parchment, \n",
    "        when read using the scytale, would reveal a message due to every nth \n",
    "        letter now appearing next to each other, revealing a proper message.\n",
    "    This encryption method is obsolete and should never be used to encrypt\n",
    "        data in production settings.\n",
    "    You may read more about the method here:\n",
    "        https://en.wikipedia.org/wiki/Scytale\n",
    "    You may follow this algorithm to implement a scytale-style cipher:\n",
    "    1. Take a message to be encoded and a \"shift\" number. \n",
    "        For this example, we will use \"INFORMATION_AGE\" as \n",
    "        the message and 3 as the shift.\n",
    "    2. Check if the length of the message is a multiple of \n",
    "        the shift. If it is not, add additional underscores \n",
    "        to the end of the message until it is. \n",
    "        In this example, \"INFORMATION_AGE\" is already a multiple of 3, \n",
    "        so we will leave it alone.\n",
    "    3. This is the tricky part. Construct the encoded message. \n",
    "        For each index i in the encoded message, use the character at the index\n",
    "        (i // shift) + (len(message) // shift) * (i % shift) of the raw message. \n",
    "        If this number doesn't make sense, you can play around with the cipher at\n",
    "         https://dencode.com/en/cipher/scytale to try to understand it.\n",
    "    4. Return the encoded message. In this case, \n",
    "        the output should be \"IMNNA_FTAOIGROE\".\n",
    "    Example:\n",
    "    scytale_cipher(\"INFORMATION_AGE\", 3) -> \"IMNNA_FTAOIGROE\"\n",
    "    scytale_cipher(\"INFORMATION_AGE\", 4) -> \"IRIANMOGFANEOT__\"\n",
    "    scytale_cipher(\"ALGORITHMS_ARE_IMPORTANT\", 8) -> \"AOTSRIOALRH_EMRNGIMA_PTT\"\n",
    "    Parameters\n",
    "    ----------\n",
    "    message: str\n",
    "        a string of uppercase English letters and underscores (underscores represent spaces)\n",
    "    shift: int\n",
    "        a positive int that does not exceed the length of message\n",
    "    Returns\n",
    "    -------\n",
    "    str\n",
    "        the encoded message\n",
    "    '''\n",
    "    # Replace `pass` with your code. \n",
    "    # Stay within the function. Only use the parameters as input. The function should return your answer.\n",
    "    \n",
    "    polished = message\n",
    "    if len(polished)%shift == 0:\n",
    "      polished = message\n",
    "    else:\n",
    "      while len(polished)%shift != 0:\n",
    "        polished = polished + \"_\"\n",
    "        \n",
    "    encoded = \"\"\n",
    "    \n",
    "    for i in range(len(polished)):\n",
    "        encoded = encoded + polished[(i // shift) + (len(message) // shift) * (i % shift)]\n",
    "        \n",
    "    return encoded\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "1f6e5315-02dc-4a24-91b5-8c03e2610918",
   "metadata": {},
   "outputs": [],
   "source": [
    "def scytale_decipher(message, shift):\n",
    "    '''Scytale De-cipher.\n",
    "    15 points.\n",
    "\n",
    "    Decrypts a message that was originally encrypted with the `scytale_cipher` function above.\n",
    "\n",
    "    Example:\n",
    "    scytale_decipher(\"IMNNA_FTAOIGROE\", 3) -> \"INFORMATION_AGE\"\n",
    "    scytale_decipher(\"AOTSRIOALRH_EMRNGIMA_PTT\", 8) -> \"ALGORITHMS_ARE_IMPORTANT\"\n",
    "    scytale_decipher(\"IRIANMOGFANEOT__\", 4) -> \"INFORMATION_AGE_\"\n",
    "\n",
    "    There is no further brief for this number.\n",
    "    \n",
    "    Parameters\n",
    "    ----------\n",
    "    message: str\n",
    "        a string of uppercase English letters and underscores (underscores represent spaces)\n",
    "    shift: int\n",
    "        a positive int that does not exceed the length of message\n",
    "\n",
    "    Returns\n",
    "    -------\n",
    "    str\n",
    "        the decoded message\n",
    "    '''\n",
    "    # Replace `pass` with your code. \n",
    "    # Stay within the function. Only use the parameters as input. The function should return your answer.\n",
    "    \n",
    "    polished = message[1:]\n",
    "    decode = \"\"\n",
    "    i = 1\n",
    "    until = shift\n",
    "    \n",
    "    while len(decode) < len(polished):\n",
    "        if i > len(polished):\n",
    "            i = 1\n",
    "        if until == 1:\n",
    "            decode = decode + polished[i-1]\n",
    "            i = i + 1\n",
    "            until = shift\n",
    "        else:\n",
    "            i = i + 1\n",
    "            until = until - 1\n",
    "        \n",
    "    return message[0] + decode\n",
    "        \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1aaeb3b2-baec-4468-9ec1-9091d1a2519d",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
